### ISSUE TITLE
Png is loaded incorrectly

### ISSUE THREAD

**Issue by yglukhov** [jangko/nimPNG#1]
The following code, which just loads and saves a PNG produces artifacts with image attached:

``` nim
let png = loadPNG32(original_path)
discard savePNG32(output_path, png.data, png.width, png.height)
```

Original image: edit: removed
Output image: edit: removed

**Comment by jangko** [comment]
this is a bug in the encoder(savePNG), perhaps in the filter/interlace section. 
it will take some time to fix it.

**Comment by yglukhov** [comment]
I've observed similar artifacts when using saveBMP from nimBMP. That's why I thought the problem is in the loader. But if it's encoder, then nimBMP is also wrong.

**Comment by jangko** [comment]
that is really strange, i don't experience the same thing with saveBMP, only with savePNG.
the decoder(loadPNG) is ok.

**Comment by yglukhov** [comment]
Ok, sorry, my mistake. saveBMP is ok.

**Comment by yglukhov** [comment]
Works, thank you!
