### ISSUE TITLE
nimPNG always fails unless in release mode

### ISSUE THREAD

**Issue by andreaferretti** [jangko/nimPNG#20]
For instance, if I try to run the code from https://github.com/jangko/nimPNG/issues/9 on the image posted there, I get an assertion failure.

```nim
import nimPNG
let data = loadPNG32("sample.png")
assert(not data.isNil)
```

```
djerzinski:nim andrea$ nim c -r example
...
example.nim(7)           example
system.nim(3788)         failedAssertImpl
system.nim(3781)         raiseAssert
system.nim(2843)         sysFatal
Error: unhandled exception: not isNil(data)  [AssertionError]
```

**But** if I run the same code with `-d:release`, everything seems to work fine :-?

**Comment by jangko** [comment]
I cannot reproduce it.
my development machine is a windows 10 64bit
Nim latest devel branch
looks like linux build is failed

**Comment by andreaferretti** [comment]
Happens on a Mac, with latest Nim

**Comment by jangko** [comment]
ok, I will investigate it. strange enough because nimPNG use no platform specific code

**Comment by andreaferretti** [comment]
Great, thank you for the quick fix!
