### ISSUE TITLE
Tests fail when using --gc:arc

### ISSUE THREAD

**Issue by guzba** [jangko/nimPNG#37]
Hi and thanks for the great library. I just wanted to create an issue to track --gc:arc support.

--gc:arc info: https://forum.nim-lang.org/t/5734

To verify the issue, simply add --gc:arc to the compile cmds in the nimble file. For example `exec "nim c --gc:arc -r test.nim"`

**Comment by treeform** [comment]
Same it's breaking my library too: https://github.com/treeform/flippy/issues/7

**Comment by jangko** [comment]
`--gc:arc` doesn't works well with `shallowCopy`. 
`--gc:arc` will turn `shallowCopy` into ordinary seq and string copy. 

it will take significant amount of time to remove this shallow copy related code to satisfies both gc:arc and default gc.

**Comment by jangko** [comment]
fixed by #40. closing
