### ISSUE TITLE
This hash look up in calculateColorProfile is the slowest part of saving an image.

### ISSUE THREAD

**Issue by treeform** [jangko/nimPNG#42]
I have profiled nimPNG code saving with VTune and 45% of the time is spent on this line:
https://github.com/jangko/nimPNG/blob/676bca486ac32f9ab32a00d388a56f768cf965ed/nimPNG.nim#L2358

This line is in calculateColorProfile ... should it just be computed once? It seems like a very slow operation with the hashing taking up most of the time. Is there a way to compute calculateColorProfile only once?

![image](https://user-images.githubusercontent.com/125948/80771837-87f26e00-8b09-11ea-9b66-eb171b5f00b2.png)

![image](https://user-images.githubusercontent.com/125948/80771940-cf78fa00-8b09-11ea-8ba9-e37159344df6.png)

I used vTune with ` nim c -d:release --debugger:native` to produce this.

**Comment by jangko** [comment]
Thank you, I think I know what's wrong with the hash function.

**Comment by treeform** [comment]
Amazing improvement, from the hottest function:

![image](https://user-images.githubusercontent.com/125948/80813441-e73e9580-8b7e-11ea-928a-d1df2a6aaa57.png)

To being almost nothing:

![image](https://user-images.githubusercontent.com/125948/80813560-148b4380-8b7f-11ea-91eb-6701808f0dfc.png)

Amazing!

Now the hottest path is the compression which is expected:

![image](https://user-images.githubusercontent.com/125948/80813680-561bee80-8b7f-11ea-871c-db5bae8b2894.png)
