### ISSUE TITLE
savePNG32 actually save png32 to png24

### ISSUE THREAD

**Issue by Tormund** [jangko/nimPNG#6]
```
import nimPNG

proc main()=
  var rawData = readFile("pngData")
  discard savePNG32("bad_png.png", rawData, 2000, 2000)
  echo "DONE"

main()
```

[pngData.zip](https://github.com/jangko/nimPNG/files/420597/pngData.zip)

**Comment by jangko** [comment]
@Tormund thank you for reporting any issue,

using hex editor, I can see that your raw data's alpha channel all have value 0xFF. PNG `'normal'
` alpha channel usually will varying between 0(fully transparent) to 0xFF(fully opaque)

it means no matter which function you use(savePNG32 or savePNG24), it will produce the same result, picture without alpha channel. (the internal algorithm of nimPNG will discard alpha channel if it found out that the rawdata actually contains no transparency(e.g. all alpha channel value is 0xFF))

I think you must check your rawdata generator, especially how they produce alpha channel.
![bug6](https://cloud.githubusercontent.com/assets/2784755/17758223/ce5ecb84-6517-11e6-837b-1b04024c7d62.jpg)

**Comment by Tormund** [comment]
@jangko Thank you for explanation ;)
