### ISSUE TITLE
savePNGImpl maybe have bug?

### ISSUE THREAD

**Issue by Angluca** [jangko/nimPNG#77]
![44934d5e77deef9059b091f3e77399f3](https://user-images.githubusercontent.com/156404/236854562-a3e2aae3-8c23-4b17-8dc0-ab584ddd8535.png)
1. I use encodePNG and write file, Generate png It's ok have 130+KB
2. If use savePNG function export png only 1KB ... ( Have bug? )
https://github.com/TakWolf/nico-font-tool/pull/6

**Comment by TakWolf** [comment]
For me, everything is ok.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/6064962/236869940-13f72734-57c1-47e9-8266-c8ff2ef84890.png">

Node: 
https://github.com/TakWolf/nico-font-tool/blob/810285e58fc9c182dddfb19a8083b4fc19c2ae02/src/nico_font_tool.nim#L116

**Comment by jangko** [comment]
You use it incorrectly, both `colorType` and `bitDepth` in `savePNGImpl` describe the input data format, while the output is controlled by `settings`, a `PNGEncoder` object.

**Comment by Angluca** [comment]
Yeah, I'm newbie use it incorrectly...T^T
