### ISSUE TITLE
Doesn't work by default on Nim v2.0.0

### ISSUE THREAD

**Issue by PMunch** [jangko/nimPNG#82]
Someone brought up in the realtime chat that `import nimPNG` triggers this `Error: undeclared identifier: 'shallowCopy'` on Nim version 2.0.0. I told them to just use `--gc:refc` for now, but this should probably be fixed.

**Comment by jangko** [comment]
This have been fixed in #74, outdated copy of nimPNG?

**Comment by PMunch** [comment]
Ah, quite possible. Sorry for taking up your time
