### ISSUE TITLE
Move tests to another repo

### ISSUE THREAD

**Issue by exelotl** [jangko/nimPNG#88]
The nimPNG repo includes a `tests` folder which is quite large.  Also, some of the links in the tests are very inappropriate. I don't want kids using my game engine (which depends on nimPNG) to see that :see_no_evil: 

![image](https://github.com/jangko/nimPNG/assets/569607/3ff92cfc-1b31-47d5-860f-ec970a25d742)

If you install via Nimble, the test files don't get copied to the pkgs directory. However, they do remain if you are using [Atlas](https://github.com/nim-lang/atlas) or simply managing your own dependencies via git submodules. 

Therefore I think it would be best to move the tests to another repo.

**Comment by jangko** [comment]
nimPNG doesn't use external links for test data. maybe they come from other sources?

**Comment by exelotl** [comment]
The file in question is `urls.10k` under `nimPNG/tests/zcorpus`

**Comment by jangko** [comment]
Thank you for looking into this. I wasn't aware there are something like this in the compression test data. They were taken from other compression project. 
As a compression library developer, we basically only check if the roundtrip compress-decompress works. While the content itself I never look into.

I will remove it.
